services:
  streamlit:
    build:
      context: ./streamlit/
      dockerfile: Dockerfile
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8501:8501"
    # depends_on:
    #   - go_server
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - __pycache__/
    # volumes:
    #   - "./frontend/.streamlit/:/app/.streamlit/"
    networks:
      - web
    labels:
      - traefik.enable=true
      # - traefik.http.routers.streamlit.entrypoints=web,websecure
      - traefik.http.routers.streamlit.entrypoints=websecure
      - traefik.http.routers.streamlit.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.streamlit.tls=true
      - traefik.http.routers.streamlit.tls.certresolver=production
      - traefik.http.services.streamlit.loadbalancer.server.port=8501
