[project]
name = "ai-tutor-streamlit"
version = "0.1.0"
requires-python = ">=3.12.8"
dependencies = [
    "bs4>=0.0.2",
    "lxml>=6.0.2",
    "qrcode>=8.2",
    "requests>=2.32.5",
    "streamlit>=1.50.0",
]
