[project]
name = "python-sandbox"
version = "0.1.0"
requires-python = ">=3.12.8"
dependencies = [
    "fastapi[standard]>=0.119.1",
    "ipython>=9.6.0",
    "numpy>=2.3.4",
    "scikit-learn>=1.7.2",
    "scipy>=1.16.2",
]
